class TrackerStatus:
    NOT_NOTIFIED = 1
    NOTIFYING = 2
    NOTIFIED = 3


class TorrentStatus:
    TORRENT_STATUS_NOT_STARTED = 0
    TORRENT_STATUS_REGISTERED = 1
    TORRENT_STATUS_METADATA = 2
    TORRENT_STATUS_DOWNLOADING = 3
    TORRENT_STATUS_FINISHED = 4
